language: go
go:
- '1.8'
sudo: false

before_install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout e73500c735917e39a8b782e0632418ab70250341 && go install && cd -

install: make vendor

script:
  - make build
  - make darwin

before_deploy:
  - mkdir -p bin_release
  - CGO_ENABLED=0 GOOS=linux  GOARCH=amd64 go build -a -ldflags '-extldflags "-static" -X main.AppVersion=$TRAVIS_TAG' -o bin_release/dell-provisioner_linux-amd64
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -a -ldflags '-extldflags "-static" -X main.AppVersion=$TRAVIS_TAG' -o bin_release/dell-provisioner_darwin-amd64

deploy:
  provider: releases
  api_key:
    secure: VioaAoLeMAEb8yiDaQcmxWFJW+1qmEL6ZI3X7Ih/8oQ+gINmjCjwoYxsNix3PgQaweBOmO6uJBAGremIUFyB6u8sE5ZXo3peBLQ/E5RBPEcAWfox2K9TUuoE921DFhQo7IJxkzyM7qAxhuhir06MFncELjdX27Hfc5/to1nJ9D0e8s6Fd6x17KI+VeqyLtHrYjDzZxn1EiG+96x1/ttdbbnMscq+xyu5djLzxYYkxjIzEBwpIFbcHBm7MZu+VAcU1U6Ok1H7QYpmQCJ0DlTKOYYBRZSMr8rcweqVAQMWOzooyS9jbXztEsx+VQOB3kEN7ai4flnqO+07kXcBALh8aoOcPPhEU1zNoUbsNJHoZB/0kD6kbZQF9gmXyeS4FKCTfnJ3e0yaJ2lkZezAeDB1ffwGzpnFvEDMssYS/N1CM8PgOaxmGzdfUHr6aA8sNjTt6VmDScCeT4p8dozIlasjkX/gAx+W5Hdo1zMyVI8dNTH50/iNTIahlrxmojhAP6ObH32nP6Ft6mTgw1OTZRgc02szIlulkPd5YRwoGTAOrTEhqNgbqFtS45cteJQKYmle1Gf3P1T+QXwKXPCRd6iLM+/FkYRrRba6cJH5W4oyELO8MPpdOb/fWv76PZRsNFkoXboJMyUimz2k3L4J2WpsklijePEGZeZD19THhiEyYkE=
  file_glob: true
  file: bin_release/*
  skip_cleanup: true
  on:
    tags: true
  go: 1.8
